# Generated by Django 3.1.4 on 2020-12-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('eventsessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventSessions',
            new_name='EventSession',
        ),
    ]
